# name: black-action
# on: [push, pull_request]
# jobs:
#   linter_name:
#     name: runner / black formatter
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: rickstaa/action-black@v1
#         with:
#           black_args: ". --check"


name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e . plotting
    - name: Lint with black
      run: |
        black --check .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
     
    - name: Lint with isort
      run: |
        pip install isort
        isort .
        ...
    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle .
        ...
    - name: Lint with mypy
      run: |
        pip install mypy
        mypy .
        ...
