name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
        

      - name: Lint with isort
        run: |
          pip install isort
          isort .
          ...
      - name: Lint with pycodestyle
        run: |
          pip install pycodestyle
          pycodestyle .
          ...
      - name: Lint with mypy
        run: |
          pip install mypy
          mypy .
          ...
